version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - api/.env
    environment:
      - PORT=8000
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - postgres
    command: sh -c "uv run uvicorn api.main:app --host 0.0.0.0 --port ${PORT} --reload"

  worker:
    build:
      context: .
      dockerfile: api/Dockerfile.worker
    env_file:
      - api/.env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - postgres
    command: sh -c "uv run celery -A api.celery_app.celery worker --loglevel=INFO"

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:10000"
    environment:
      - PORT=10000
      - API_BASE_URL=http://localhost:8000/

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


