[build]
  command = "echo 'This is a FastAPI backend, not a static site'"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/api/v1/health"
  status = 200

[functions]
  directory = "netlify/functions"
