/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutDemoRouteImport } from './routes/layout-demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ApiTestRouteImport } from './routes/api-test'
import { Route as IndexRouteImport } from './routes/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutDemoRoute = LayoutDemoRouteImport.update({
  id: '/layout-demo',
  path: '/layout-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestRoute = ApiTestRouteImport.update({
  id: '/api-test',
  path: '/api-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-test': typeof ApiTestRoute
  '/dashboard': typeof DashboardRoute
  '/layout-demo': typeof LayoutDemoRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-test': typeof ApiTestRoute
  '/dashboard': typeof DashboardRoute
  '/layout-demo': typeof LayoutDemoRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-test': typeof ApiTestRoute
  '/dashboard': typeof DashboardRoute
  '/layout-demo': typeof LayoutDemoRoute
  '/login': typeof LoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api-test' | '/dashboard' | '/layout-demo' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api-test' | '/dashboard' | '/layout-demo' | '/login'
  id: '__root__' | '/' | '/api-test' | '/dashboard' | '/layout-demo' | '/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiTestRoute: typeof ApiTestRoute
  DashboardRoute: typeof DashboardRoute
  LayoutDemoRoute: typeof LayoutDemoRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layout-demo': {
      id: '/layout-demo'
      path: '/layout-demo'
      fullPath: '/layout-demo'
      preLoaderRoute: typeof LayoutDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-test': {
      id: '/api-test'
      path: '/api-test'
      fullPath: '/api-test'
      preLoaderRoute: typeof ApiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiTestRoute: ApiTestRoute,
  DashboardRoute: DashboardRoute,
  LayoutDemoRoute: LayoutDemoRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
