"""migrating columns from legacy API

Revision ID: 38062b60878b
Revises: 93ec8eeaddc5
Create Date: 2025-08-12 15:59:36.420571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38062b60878b'
down_revision = '93ec8eeaddc5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('platform_data', sa.JSON(), nullable=True))
    op.alter_column('documents', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'score',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('documents', 'platform_data')
    op.drop_column('documents', 'priority')
    # ### end Alembic commands ###
