"""integrations tables

Revision ID: 4181ba22a7c9
Revises: ad1d8726dc19
Create Date: 2025-09-01 05:30:06.605212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4181ba22a7c9'
down_revision = 'ad1d8726dc19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
