"""added score to document

Revision ID: 93ec8eeaddc5
Revises: 5182be5c1f9f
Create Date: 2025-08-12 15:39:30.024927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ec8eeaddc5'
down_revision = '5182be5c1f9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'score')
    # ### end Alembic commands ###
